batch_size: 1
checkpoint_time: 10000
encodings: true
epoch: 821
epochs_per_mip: 4
feature_maps: [12, 12, 12, 12, 12]
gamma: 1
gamma_step: 30
gpus: '1'
height: 5
initialized_list: [true, true, true, true, true]
iteration: 2468
lambda1: 100000.0
levels: !!python/object/apply:builtins.slice [null, null, null]
log_time: 1
lr: 0.003
name: test_encodings_all_samples_mGPU_c2e_v04_lsm
num_epochs: 1000000
penalty: lap
plan: all
repeats: 1
seed: 5432
start_lr: 0.003
supervised: false
training_set_path: !!python/object/apply:pathlib.PosixPath [/, home, bnehoran, training_data,
  mip2_mixed_annotated.h5]
validation_set_path: !!python/object/apply:pathlib.PosixPath [/, home, bnehoran, training_data,
  minnie_mip4_annotated_prep_major_folds_curriculum_45x6x1536_sep.h5]
vis_time: 100000
wd: 0
