batch_size: 1
catastrophic_loss: 0.5
checkpoint_time: 100
encodings: true
epoch: 212
epochs_per_mip: 2
feature_maps:
- 12
- 18
- 24
- 30
- 36
- 42
gamma: 0.5
gamma_step: 5000
gpus: '3'
height: 6
initialized_list:
- true
- true
- true
- true
- true
- true
iteration: null
lambda1: 10000000.0
levels: null
log_time: 1
lr: 0.0001
name: nk_vf_30_minnie_jit_mip4
num_epochs: 1000000000
num_samples: null
penalty: rig
plan: all
repeats: 1
seed: null
skip_aug: true
start_lr: 0.0001
supervised: false
training_set_path: !!python/object/apply:pathlib.PosixPath
- /
- usr
- people
- nkemnitz
- SEAMLeSS
- jit_mip4_fold1200_train.h5
validation_set_path: !!python/object/apply:pathlib.PosixPath
- /
- usr
- people
- nkemnitz
- SEAMLeSS
- jit_mip4_fold10_train.h5
vis_time: 50
wd: 0
