apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: seamless-manuel-100
  name: seamless-manuel-100
spec:
  replicas: 250
  selector:
    matchLabels:
      run: seamless-manuel-100
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: seamless-manuel-100
    spec:
      containers:
      - image: seunglab/seamless:manuel-sergiy-opt-mip4-fixed
        name: seamless-manuel-100
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "python inference/worker.py --processes 3 --gpu_processes 2 --queue_name manuel-igneous --lease_seconds 40"]
        resources: 
          limits:
            nvidia.com/gpu: 1
        volumeMounts:
        - name: secrets
          mountPath: /root/.cloudvolume/secrets
          readOnly: true
      dnsPolicy: Default
      volumes:
      - name: secrets
        secret:
          secretName: secrets
status: {}
