apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: seamless-manuel-2
  name: seamless-manuel-2
spec:
  replicas: 50 
  selector:
    matchLabels:
      run: seamless-manuel-2
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: seamless-manuel-2
    spec:
      containers:
      - image: seunglab/seamless:manuel-coarse1000
        name: seamless
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "python inference/worker.py --processes 1 --gpu_processes 1 --queue_name manuel-igneous --lease_seconds 40"]
        resources: 
          limits:
            nvidia.com/gpu: 1
        volumeMounts:
        - name: secrets
          mountPath: /root/.cloudvolume/secrets
          readOnly: true
      dnsPolicy: Default
      volumes:
      - name: secrets
        secret:
          secretName: secrets
status: {}
