apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: seamless-1
  name: seamless-1
spec:
  replicas: 50 
  selector:
    matchLabels:
      run: seamless
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: seamless
    spec:
      containers:
      - image: seunglab/seamless:zhen_test
        name: seamless
        resources:
          limits:
            memory: "190Gi"
            cpu: "31"
          requests:
            memory: "190Gi"
            cpu: "31"
       #imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "sh run.sh"]
        volumeMounts:
        - name: secrets
          mountPath: /root/.cloudvolume/secrets
          readOnly: true
      dnsPolicy: Default
      volumes:
      - name: secrets
        secret:
          secretName: secrets
status: {}
