apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: seamless
  name: seamless
spec:
  replicas: 64 
  selector:
    matchLabels:
      run: seamless
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: seamless
    spec:
      containers:
      - image: seunglab/seamless:pairwise
        name: seamless
        imagePullPolicy: Always
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: awssecret
                key: acc_key
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: awssecret
                key: secret_key
          - name: AWS_DEFAULT_REGION
            valueFrom:
              secretKeyRef:
                name: awssecret
                key: region
        command: ["/bin/sh"]
        args: ["-c", "python3 inference/worker.py --model_path ../models/sergiy_trans_minnie_v1_m8m10_trainedforvv --src_path gs://microns-seunglab/minnie_v0/raw_image --src_mask_path gs://seunglab2/minnie_v1/alignment/net_masks/resin_mask_v3 --src_mask_mip 8 --src_mask_val 250 --tgt_mask_path gs://seunglab2/minnie_v1/alignment/net_masks/resin_mask_v3 --tgt_mask_mip 8 --tgt_mask_val 250 --dst_path gs://seunglab2/minnie_v1/alignment/coarse/tmacrina_minnie10_serial --mip 6 --max_mip 8 --render_low_mip 2 --render_high_mip 8 --bbox_start 80000 80000 20823 --bbox_stop 430000 360000 20827 --bbox_mip 0 --should_contrast --max_displacement 4096 --size 8 --disable_flip_average --old_vectors --tgt_radius 3 --queue_name deepalign1"]
        resources: 
          limits:
            nvidia.com/gpu: 1
        volumeMounts:
        - name: secrets
          mountPath: /root/.cloudvolume/secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: secrets
status: {}
