apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: seamless
  name: seamless
spec:
  replicas: 2 
  selector:
    matchLabels:
      run: seamless
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: seamless
    spec:
      containers:
      - image: seunglab/seamless:pairwise
        name: seamless
        imagePullPolicy: Always
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: awssecret
                key: acc_key
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: awssecret
                key: secret_key
          - name: AWS_DEFAULT_REGION
            valueFrom:
              secretKeyRef:
                name: awssecret
                key: region
        command: ["/bin/sh"]
        args: ["-c", "python3 inference/worker.py --model_path ../models/vector_fixer30 --src_path gs://seunglab2/minnie_v1/alignment/coarse/tmacrina_minnie10_serial/upsampled_image --dst_path gs://seunglab2/minnie_v1/alignment/fine/tmacrina_minnie10_serial --mip 2 --max_mip 8 --render_low_mip 2 --render_high_mip 8 --bbox_start 80000 80000 20823 --bbox_stop 430000 360000 20829 --bbox_mip 0 --should_contrast --max_displacement 4096 --size 8 --disable_flip_average --old_vectors --tgt_radius 3 --queue_name deepalign3"]
        resources: 
          limits:
            nvidia.com/gpu: 1
        volumeMounts:
        - name: secrets
          mountPath: /root/.cloudvolume/secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: secrets
status: {}
