apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
    labels:
      run: seamless
    name: seamless
    namespace: default
  spec:
    progressDeadlineSeconds: 600
    replicas: 3
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        run: seamless
    strategy:
      rollingUpdate:
        maxSurge: 100%
        maxUnavailable: 100%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          run: seamless
      spec:
        containers:
        - args:
          - -c
          - python inference/worker.py --processes 8 --queue_name deepalign0 --lease_seconds
            60
          command:
          - /bin/sh
          image: seunglab/seamless:fcorr
          imagePullPolicy: Always
          name: seamless
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          resources:
            limits:
              cpu: 7
          volumeMounts:
          - mountPath: /root/.cloudvolume/secrets
            name: secrets
            readOnly: true
        dnsPolicy: Default
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: secrets
          secret:
            defaultMode: 420
            secretName: secrets
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""