apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: seamless-2
  name: seamless-2
spec:
  replicas: 0
  selector:
    matchLabels:
      run: seamless-2
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: seamless-2
    spec:
      containers:
      - image: gcr.io/zetta-aibs-mouse-001/seamless-fine-fixed-seethruv2
        name: seamless-2
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "python inference/worker.py --processes 4 --queue_name manuel-seamless --lease_seconds 10"]
        resources: 
          limits:
            nvidia.com/gpu: 1
        volumeMounts:
        - name: secrets
          mountPath: /root/.cloudvolume/secrets
          readOnly: true
        - mountPath: /root/.aws/credentials
          name: credentials
          readOnly: true
      dnsPolicy: Default
      volumes:
      - name: secrets
        secret:
          secretName: secrets
status: {}
