apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: seamless
  name: seamless
spec:
  replicas: 12
  selector:
    matchLabels:
      run: seamless
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: seamless
    spec:
      containers:
      - image: seunglab/pairwise_inference:gpu_test
        name: seamless
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: awssecret
                key: acc_key
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: awssecret
                key: secret_key
          - name: AWS_DEFAULT_REGION
            valueFrom:
              secretKeyRef:
                name: awssecret
                key: region
        command: ["/bin/sh"]
        args: ["-c", "python3 SEAMLeSS/inference/worker.py --model_path SEAMLeSS/inference/model_repository/vector_fixer30_fine_tuning_low_mip_e176_t200_.pt --mip 2 --max_mip 6 --render_mip 2 --num_targets 2 --xs 90000 --xe 185000 --ys 15000 --ye 100000 --zs 1100 --stack_size 350 --source --source gs://neuroglancer/drosophila_v0/image_v14_single_slices --edge_pad 256 --should_contrast 1 --max_displacement 2048 --size 8 --out_name zhen_test_distributed_Nov08 --queue_name deepalign --run_pairs --p_render"]
        resources: 
          limits:
            nvidia.com/gpu: 1
        volumeMounts:
        - name: secrets
          mountPath: /root/.cloudvolume/secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: secrets
        #hostPath:
        #  path: /usr/people/zhenj/.cloudvolume/secrets
status: {}
