apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: seamless
  name: seamless
spec:
  replicas: 3
  selector:
    matchLabels:
      run: seamless
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: seamless
    spec:
      containers:
      - image: seunglab/nflow_inference:gpu-test
        name: seamless
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: awssecret
                key: acc_key
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: awssecret
                key: secret_key
          - name: AWS_DEFAULT_REGION
            valueFrom:
              secretKeyRef:
                name: awssecret
                key: region
        command: ["/bin/sh"]
        args: ["-c", "python3 SEAMLeSS/inference/worker.py --model_path SEAMLeSS/inference/model_repository/vector_fixer30_fine_tuning_low_mip_e9_t200_.pt --mip 2 --max_mip 6 --render_mip 2 --num_targets 2 --xs 0 --xe 20000 --ys 0 --ye 20000 --zs 357 --stack_size 20 --source gs://neuroglancer/pinky40_alignment/prealigned_rechunked --edge_pad 256 --should_contrast 1 --max_displacement 2048 --size 8 --out_name pinky40_zhen_test --queue_name deepalign"]
        resources: 
          limits:
            nvidia.com/gpu: 1
        volumeMounts:
        - name: secrets
          mountPath: /root/.cloudvolume/secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: secrets
        #hostPath:
        #  path: /usr/people/zhenj/.cloudvolume/secrets
status: {}
