batch_size: 1
checkpoint_time: 100
encodings: false
epoch: 0
epochs_per_mip: 4
feature_maps: [3, 6, 12]
gamma: 0.1
gamma_step: 30
gpus: '3'
height: 3
initialized_list: [true, false, false]
iteration: 551
lambda1: 0.1
levels: 0
log_time: 1
lr: 2.0e-06
name: inverter_v0
num_epochs: 1000000
penalty: lap
plan: random_one
seed: 4568
start_lr: 2.0e-06
supervised: true
training_set_path: !!python/object/apply:pathlib.PosixPath [/, usr, people, bnehoran,
  training_data, mip2_mixed.h5]
validation_set_path: null
vis_time: 50
wd: 0
