batch_size: 6
checkpoint_time: 10000
encodings: true
epoch: 614
epochs_per_mip: 4
feature_maps: [12, 12, 12, 12, 12]
gamma: 1
gamma_step: 30
gpus: 2,3,4,5,6,7
height: 5
initialized_list: [true, true, true, true, true]
iteration: null
lambda1: 3000.0
levels: null
log_time: 1
lr: 3.0e-05
name: encodings_all_samples_mGPU_c2e
num_epochs: 1000000
penalty: lap
plan: all
seed: 5432
start_lr: 3.0e-05
supervised: false
training_set_path: !!python/object/apply:pathlib.PosixPath [/, usr, people, runzhey,
  training_data, minnie_mip4_annotated_major_folds_curriculum_45x6x1536.h5]
validation_set_path: null
vis_time: 10000
wd: 0
