apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1beta1","kind":"Deployment","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"run":"seamless"},"name":"seamless","namespace":"default"},"spec":{"replicas":100,"selector":{"matchLabels":{"run":"seamless"}},"strategy":{"rollingUpdate":{"maxSurge":"100%","maxUnavailable":"100%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"run":"seamless"}},"spec":{"containers":[{"args":["-c","python inference/worker.py --processes 4 --gpu_processes 1 --queue_name nkem-seamless-1 --lease_seconds 50"],"command":["/bin/sh"],"image":"seunglab/seamless:nkem-precoarse-minnie","imagePullPolicy":"Always","name":"seamless","resources":{"limits":{"nvidia.com/gpu":1}},"volumeMounts":[{"mountPath":"/root/.cloudvolume/secrets","name":"secrets","readOnly":true}]}],"dnsPolicy":"Default","volumes":[{"name":"secrets","secret":{"secretName":"secrets"}}]}}},"status":{}}
  creationTimestamp: "2019-10-25T20:52:26Z"
  generation: 15
  labels:
    run: seamless-blockmatch
  name: seamless-blockmatch
  namespace: default
  resourceVersion: "20634751"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/seamless
  uid: 5a1d53d3-f769-11e9-8bdb-4201ac10002a
spec:
  progressDeadlineSeconds: 600
  replicas: 4 
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: seamless-blockmatch
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: seamless-blockmatch
    spec:
      containers:
      - args:
        - -c
        - python inference/worker.py --processes 6 --gpu_processes 1 --queue_name
          sergiy_inference_test --lease_seconds 50
        command:
        - /bin/sh
        image: seunglab/seamless:sergiy_blockmatch
        imagePullPolicy: Always
        name: seamless
        resources:
          limits:
            nvidia.com/gpu: "1"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/.cloudvolume/secrets
          name: secrets
          readOnly: true
      dnsPolicy: Default
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: secrets
        secret:
          defaultMode: 420
          secretName: secrets
status:
  conditions:
  - lastTransitionTime: "2019-10-25T20:52:26Z"
    lastUpdateTime: "2019-10-25T20:52:26Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-10-30T12:03:23Z"
    lastUpdateTime: "2019-10-30T21:50:05Z"
    message: ReplicaSet "seamless-74b49b464" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 15
