apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "25"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"4"},"creationTimestamp":"2019-10-25T20:52:26Z","generation":15,"labels":{"run":"seamless"},"name":"seamless","namespace":"default","resourceVersion":"20634751","selfLink":"/apis/extensions/v1beta1/namespaces/default/deployments/seamless","uid":"5a1d53d3-f769-11e9-8bdb-4201ac10002a"},"spec":{"progressDeadlineSeconds":600,"replicas":0,"revisionHistoryLimit":2,"selector":{"matchLabels":{"run":"seamless"}},"strategy":{"rollingUpdate":{"maxSurge":"100%","maxUnavailable":"100%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"run":"seamless"}},"spec":{"containers":[{"args":["-c","python inference/worker.py --processes 6 --gpu_processes 1 --queue_name sergiy_seampless_test --lease_seconds 50"],"command":["/bin/sh"],"image":"seunglab/seamless:sergiy_blockmatch","imagePullPolicy":"Always","name":"seamless","resources":{"limits":{"nvidia.com/gpu":"1"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/root/.cloudvolume/secrets","name":"secrets","readOnly":true}]}],"dnsPolicy":"Default","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"name":"secrets","secret":{"defaultMode":420,"secretName":"secrets"}}]}}},"status":{"conditions":[{"lastTransitionTime":"2019-10-25T20:52:26Z","lastUpdateTime":"2019-10-25T20:52:26Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2019-10-30T12:03:23Z","lastUpdateTime":"2019-10-30T21:50:05Z","message":"ReplicaSet \"seamless-74b49b464\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":15}}
  creationTimestamp: "2019-10-25T20:52:26Z"
  generation: 44
  labels:
    run: seamless
  name: seamless
  namespace: default
  resourceVersion: "141598912"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/seamless
  uid: 5a1d53d3-f769-11e9-8bdb-4201ac10002a
spec:
  progressDeadlineSeconds: 600
  replicas: 800
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: seamless
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: seamless
    spec:
      containers:
      - args:
        - -c
        - python inference/worker.py --processes 1 --gpu_processes 1 --queue_name
          deepalign-fine-1 --completed_queue_name deepalign-fine-completion-1 --lease_seconds
          80
        command:
        - /bin/sh
        image: seunglab/seamless:sergiy-fine-final-x38
        imagePullPolicy: Always
        name: seamless
        resources:
          limits:
            nvidia.com/gpu: "1"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/.cloudvolume/secrets
          name: secrets
          readOnly: true
      dnsPolicy: Default
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: secrets
        secret:
          defaultMode: 420
          secretName: secrets
status:
  availableReplicas: 344
  conditions:
  - lastTransitionTime: "2019-10-25T20:52:26Z"
    lastUpdateTime: "2019-10-25T20:52:26Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-11-06T21:55:30Z"
    lastUpdateTime: "2020-02-08T04:46:00Z"
    message: ReplicaSet "seamless-7d5d9d677" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 44
  readyReplicas: 344
  replicas: 800
  unavailableReplicas: 456
  updatedReplicas: 800
