apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "46"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"9"},"creationTimestamp":"2019-10-25T20:52:26Z","generation":23,"labels":{"run":"seamless-coarse"},"name":"seamless-coarse","namespace":"default","resourceVersion":"30553245","selfLink":"/apis/extensions/v1beta1/namespaces/default/deployments/seamless","uid":"5a1d53d3-f769-11e9-8bdb-4201ac10002a"},"spec":{"progressDeadlineSeconds":600,"replicas":800,"revisionHistoryLimit":2,"selector":{"matchLabels":{"run":"seamless"}},"strategy":{"rollingUpdate":{"maxSurge":"100%","maxUnavailable":"100%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"run":"seamless"}},"spec":{"containers":[{"args":["-c","python inference/worker.py --processes 5 --gpu_processes 1 --queue_name deepalign-coarse-1 --lease_seconds 10"],"command":["/bin/sh"],"image":"seunglab/seamless:seargiy-minnie-coarse","imagePullPolicy":"Always","name":"seamless-coarse","resources":{"limits":{"nvidia.com/gpu":"1"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/root/.cloudvolume/secrets","name":"secrets","readOnly":true}]}],"dnsPolicy":"Default","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"name":"secrets","secret":{"defaultMode":420,"secretName":"secrets"}}]}}},"status":{"availableReplicas":236,"conditions":[{"lastTransitionTime":"2019-10-25T20:52:26Z","lastUpdateTime":"2019-10-25T20:52:26Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2019-11-05T22:53:19Z","lastUpdateTime":"2019-11-06T17:16:59Z","message":"ReplicaSet \"seamless-9fc77c749\" is progressing.","reason":"ReplicaSetUpdated","status":"True","type":"Progressing"}],"observedGeneration":23,"readyReplicas":236,"replicas":800,"unavailableReplicas":564,"updatedReplicas":800}}
  creationTimestamp: "2019-11-12T10:26:32Z"
  generation: 121
  labels:
    run: seamless-coarse
  name: seamless-coarse
  namespace: default
  resourceVersion: "50737632"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/seamless-coarse
  uid: e580e7c4-0536-11ea-9f17-4201ac100044
spec:
  progressDeadlineSeconds: 600
  replicas: 800
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: seamless
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: seamless
    spec:
      containers:
      - args:
        - -c
        - python inference/worker.py --processes 1  --gpu_processes 1 --queue_name
          deepalign-coarse-1 --lease_seconds 65
        command:
        - /bin/sh
        image: seunglab/seamless:sergiy-coarse-final-x10
        imagePullPolicy: Always
        name: seamless-coarse
        resources:
          limits:
            nvidia.com/gpu: "1"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/.cloudvolume/secrets
          name: secrets
          readOnly: true
      dnsPolicy: Default
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: secrets
        secret:
          defaultMode: 420
          secretName: secrets
status:
  availableReplicas: 173
  conditions:
  - lastTransitionTime: "2019-11-12T10:26:32Z"
    lastUpdateTime: "2019-11-12T10:26:32Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-02-05T07:50:50Z"
    lastUpdateTime: "2020-02-07T00:25:10Z"
    message: ReplicaSet "seamless-coarse-6495ff5657" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 121
  readyReplicas: 173
  replicas: 800
  unavailableReplicas: 627
  updatedReplicas: 800
